model:
  cuda: ${cuda}
  ly_model: HorizonNetV2
  ckpt: ${trained_models.${ckpt}.ckpt}
  seed: ${seed}
  inference:
    batch_size: 4
    num_workers: 4

dataset: hm3d_mvl #from datasets.yaml
ckpt: hn_mp3d #from trained_models.yaml
dataset_code: ${ckpt}__${dataset}
mvl_dataset:
  dataset_name: ${dataset}
  img_dir: ${datasets.${dataset}.img_dir}
  labels_dir: ${datasets.${dataset}.labels_dir}
  geometry_info_dir: ${datasets.${dataset}.geometry_info_dir}
  scene_list: ${datasets.${dataset}.scene_list_dir}/scene_list__training_set.json
  size: -1
  resolution: ${datasets.${dataset}.resolution}
  seed: ${seed}

experiment_name: ${script}
output_dir: /media/Pluto/kike/ray_casting_mlc_ws/pre_computed_data/${experiment_name}/${dataset_code}
log_dir: ${output_dir}/logs

pre_computed_data:
  dir_mlc: /media/Pluto/kike/ray_casting_mlc_ws/pre_computed_data/pre_compute_mlc/${dataset_code}/label
  dir_phi_coords: /media/Pluto/kike/ray_casting_mlc_ws/pre_computed_data/pre_compute_xyz/${dataset_code}/phi_coords
  dir_xyz: /media/Pluto/kike/ray_casting_mlc_ws/pre_computed_data/pre_compute_xyz/${dataset_code}/xyz
  dir_n_cycle_ray_cast: /media/Pluto/kike/ray_casting_mlc_ws/pre_computed_data/multi_cycle_ray_casting/${dataset_code}/ray_cast_xyz
  # dir_ray_cast_xyz:

ray_casting_mlc:
  ray_tracer:
    cycles: 15
    number_rays: 1024
    fov: 360
    max_norm_dist: 0.01
    max_depth: 20
    min_depth: 0
    cuda: ${cuda}
  initial_xyz: ${mlc_phi_coord_data}
  # initial_xyz: ${filter_dist_data}

filter_dist_data:
  module_name: ray_casting_mlc.utils.get_xyz_filtering_by_distance
  kwargs:
    data_dir: ${pre_computed_data.dir_phi_coords}
    max_distance: 2

mlc_phi_coord_data:
  module_name: ray_casting_mlc.utils.get_xyz_from_phi_coords
  kwargs:
    data_dir: ${pre_computed_data.dir_mlc}




defaults:
  - general
  - trained_models
  - datasets
  - horizon_net
  - _self_

hydra:
  searchpath:
    - ${oc.env:RAY_CASTING_MLC_CFG_DIR}
