ExponentialLR:
  name: ExponentialLR
  lr_decay_rate: 0.90

Adam_optimizer:
  name: Adam
  lr: 0.00005
  beta1: 0.9
  weight_decay: 0.0

cuda: 0
seed: 594277
model:
  device: cuda:${model.cuda}
  cuda: ${cuda}
  ly_model: HorizonNet
  ckpt: ${trained_models.${ckpt}.ckpt}
  seed: ${seed}
  train: TBD 
  test: TBD
  inference: TBD
  loss: TBD

defaults:
  - general
  - trained_models
  - _self_
