pseudo_labels:
# !
# !   MLC pseudo labels
# !
  # * hm3d_mvl
  hm3d_mvl__mlc:
    v1.0:
    # v230817:
      labels_dir: /media/Pluto/kike/mlc_pp_project/cvpr24/pseudo_labels/mlc/230817/hn_mp3d__hm3d_mvl/label
  # * mp3d_fpe_mvl
  mp3d_fpe_mvl__mlc: 
    v1.0:
    # v230817:
      labels_dir: /media/Pluto/kike/mlc_pp_project/cvpr24/pseudo_labels/mlc/230817/hn_mp3d__mp3d_fpe_mvl/label
  # * ZIND_MVL
  zind_mvl__mlc:
    v1.0:
    # v231007:
      labels_dir: /media/Pluto/kike/mlc_pp_project/cvpr24/pseudo_labels/mlc/231007/hn_mp3d__zind_mvl/label

# !
# !   MLC-BEV pseudo labels
# !
# * hm3d-mvl
  hm3d_mvl__bev:
    v230922:
      labels_dir: /media/Pluto/kike/mlc_pp_project/cvpr24/pseudo_labels/mlc_bev/230822/hn_mp3d__hm3d_mvl/label
      scene_list: /media/Pluto/kike/mlc_pp_project/mlc_pp/mlc_pp/assets/experiments/policy_selection/cooperative_training/mlc/230919/selected_scenes_0.80_0.80.json
    v231008: # > The best pseudo labels 
      labels_dir: /media/Pluto/kike/mlc_pp_project/cvpr24/pseudo_labels/mlc/231008/hn_mp3d__hm3d_mvl/label
    v231025.1:
      labels_dir: /media/Pluto/kike/mlc_pp_project/cvpr24/pre_computed_data/231025/hn_mp3d__hm3d_mvl/label_std_from_mlc_xyz
    v231025.2:
      labels_dir: /media/Pluto/kike/mlc_pp_project/cvpr24/pre_computed_data/231025/hn_mp3d__hm3d_mvl/label_std_from_all_xyz


# * mp3d_fpe_mvl
  mp3d_fpe_mvl__bev: 
    v230924:
      labels_dir: /media/Pluto/kike/mlc_pp_project/cvpr24/pseudo_labels/mlc_bev_cam_dist/230924/hn_mp3d__mp3d_fpe_mvl/label
      scene_list: /media/Pluto/kike/mlc_pp_project/mlc_pp/mlc_pp/assets/experiments/policy_selection/cooperative_training/mlc_v.230817_mlc_bev_cam_dist.230924_hn_mp3d__mp3d_fpe_mvl/selected_scenes_0.80_0.80.json
    v231006_21:
      labels_dir: /media/Pluto/kike/mlc_pp_project/cvpr24/pseudo_labels/mlc_bev/hn_mp3d__mp3d_fpe_mvl__231006.21/label
    v231008: # > The best pseudo labels 
      labels_dir: /media/Pluto/kike/mlc_pp_project/cvpr24/pseudo_labels/mlc/231008/hn_mp3d__mp3d_fpe_mvl/label
    v231025.1:
      labels_dir: /media/Pluto/kike/mlc_pp_project/cvpr24/pre_computed_data/231025/hn_mp3d__mp3d_fpe_mvl/label_std_from_mlc_xyz
    v231025.2:
      labels_dir: /media/Pluto/kike/mlc_pp_project/cvpr24/pre_computed_data/231025/hn_mp3d__mp3d_fpe_mvl/label_std_from_all_xyz
    

# * zind_mvl
  zind_mvl__bev:
    v231008:     # > The best pseudo labels 
      labels_dir: /media/Pluto/kike/mlc_pp_project/cvpr24/pseudo_labels/mlc/231008/hn_mp3d__zind_mvl/label
    v231025_1:
      labels_dir: /media/Pluto/kike/mlc_pp_project/cvpr24/pre_computed_data/231025/hn_mp3d__zind_mvl/label_std_from_mlc_xyz
    v231025_2:
      labels_dir: /media/Pluto/kike/mlc_pp_project/cvpr24/pre_computed_data/231025/hn_mp3d__zind_mvl/label_std_from_all_xyz
    